version: 0.0
os: linux

files:
  - source:  deployment_number.txt
    destination: /opt/last_deployment.txt
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
