#!/bin/bash

# login to ecr
DOCKER_LOGIN=$(aws ecr get-login --region ap-southeast-2 | sed "s/\-e\snone//")
$DOCKER_LOGIN

ACCOUNT=$(aws sts get-caller-identity --query Account --output text)

# pull new container
docker pull $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/cicdasacodedemo:latest

# start container
docker run --rm -p80:3000 -d --name demo-container $ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/cicdasacodedemo:latest
